using Microsoft.AspNetCore.Mvc;
using StudentManagementSystem.Models;
using System.Diagnostics;

namespace StudentManagementSystem.Controllers
{
    /// <summary>
    /// HomeController — auto-generated by Visual Studio.
    /// We keep it to satisfy the default error route (/Home/Error)
    /// defined in Program.cs for non-development environments.
    ///
    /// The Index action redirects straight to the Login page so
    /// the Home route is never exposed to end users.
    /// </summary>
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        // Redirect root URL → Login
        public IActionResult Index()
        {
            return RedirectToAction("Login", "Account");
        }

        // Used by app.UseExceptionHandler("/Home/Error") in non-Development mode.
        // RequestId lets developers trace the failed request in logs.
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel
            {
                RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier,
                Message   = "An unexpected error occurred. Please try again."
            });
        }
    }
}
